<?php

namespace App\Services\Reports;

use Barryvdh\DomPDF\Facade\Pdf;
use Illuminate\Support\Carbon;
use Illuminate\Support\Str;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * Turns a report result into a downloadable Excel workbook or PDF document.
 *
 * Both exports are driven by the same report definition as the on-screen table,
 * so a column added to a report appears everywhere without further work.
 */
class ReportExportService
{
    private const HEADER_FILL = '0F5D4C';
    private const HEADER_TEXT = 'FFFFFF';

    /**
     * @param  array<int, array<string, mixed>>  $rows
     * @param  array<string, mixed>  $summary
     * @param  array<string, mixed>  $context
     */
    public function excel(ReportDefinition $definition, array $rows, array $summary, array $context = []): StreamedResponse
    {
        $spreadsheet = new Spreadsheet;
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle(Str::limit($definition->title, 28, ''));

        $columnCount = count($definition->columns);
        $lastColumn = $this->columnLetter($columnCount);

        // Title block
        $sheet->setCellValue('A1', $definition->title);
        $sheet->mergeCells('A1:'.$lastColumn.'1');
        $sheet->getStyle('A1')->getFont()->setBold(true)->setSize(14);

        $sheet->setCellValue('A2', sprintf(
            '%s  |  Generated %s  |  Generated by %s',
            $context['company'] ?? 'PharmaVerify',
            Carbon::now()->format('d M Y H:i'),
            $context['generated_by'] ?? '-'
        ));
        $sheet->mergeCells('A2:'.$lastColumn.'2');
        $sheet->getStyle('A2')->getFont()->setSize(9)->getColor()->setRGB('5F6B6A');

        $filterLine = $this->describeFilters($context['filters'] ?? []);
        $sheet->setCellValue('A3', $filterLine !== '' ? 'Filters: '.$filterLine : 'Filters: none applied');
        $sheet->mergeCells('A3:'.$lastColumn.'3');
        $sheet->getStyle('A3')->getFont()->setSize(9)->getColor()->setRGB('5F6B6A');

        // Header row
        $headerRow = 5;
        $columnIndex = 1;

        foreach ($definition->columns as $column) {
            $sheet->setCellValue([$columnIndex, $headerRow], $column['label']);
            $sheet->getColumnDimension($this->columnLetter($columnIndex))
                ->setWidth((float) ($column['width'] ?? $this->defaultWidth($column['type'] ?? 'text')));
            $columnIndex++;
        }

        $headerRange = 'A'.$headerRow.':'.$lastColumn.$headerRow;
        $sheet->getStyle($headerRange)->getFont()->setBold(true)->getColor()->setRGB(self::HEADER_TEXT);
        $sheet->getStyle($headerRange)->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB(self::HEADER_FILL);
        $sheet->getStyle($headerRange)->getAlignment()->setVertical(Alignment::VERTICAL_CENTER);
        $sheet->getRowDimension($headerRow)->setRowHeight(20);

        // Data rows
        $rowIndex = $headerRow + 1;

        foreach ($rows as $row) {
            $columnIndex = 1;

            foreach ($definition->columns as $column) {
                $value = $row[$column['key']] ?? null;
                $sheet->setCellValue([$columnIndex, $rowIndex], $this->excelValue($value, $column['type'] ?? 'text'));

                if (in_array($column['type'] ?? 'text', ['decimal', 'money', 'number'], true)) {
                    $sheet->getStyle([$columnIndex, $rowIndex])
                        ->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
                }

                $columnIndex++;
            }

            $rowIndex++;
        }

        if ($rows !== []) {
            $dataRange = 'A'.$headerRow.':'.$lastColumn.($rowIndex - 1);
            $sheet->getStyle($dataRange)->getBorders()->getAllBorders()
                ->setBorderStyle(Border::BORDER_THIN)->getColor()->setRGB('D6DEDD');
            $sheet->setAutoFilter($dataRange);
        } else {
            $sheet->setCellValue('A'.$rowIndex, 'No records matched the selected filters.');
            $rowIndex++;
        }

        // Summary block
        if ($summary !== []) {
            $rowIndex++;
            $sheet->setCellValue('A'.$rowIndex, 'Summary');
            $sheet->getStyle('A'.$rowIndex)->getFont()->setBold(true);
            $rowIndex++;

            foreach ($summary as $label => $value) {
                $sheet->setCellValue('A'.$rowIndex, ucwords(str_replace('_', ' ', (string) $label)));
                $sheet->setCellValue('B'.$rowIndex, is_float($value) ? round($value, 3) : $value);
                $rowIndex++;
            }
        }

        $sheet->freezePane('A'.($headerRow + 1));

        $fileName = $this->fileName($definition, 'xlsx');

        return response()->streamDownload(function () use ($spreadsheet) {
            $writer = new Xlsx($spreadsheet);
            $writer->save('php://output');
            $spreadsheet->disconnectWorksheets();
        }, $fileName, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        ]);
    }

    /**
     * @param  array<int, array<string, mixed>>  $rows
     * @param  array<string, mixed>  $summary
     * @param  array<string, mixed>  $context
     */
    public function pdf(ReportDefinition $definition, array $rows, array $summary, array $context = [])
    {
        $pdf = Pdf::loadView('reports.pdf', [
            'definition' => $definition,
            'rows' => $rows,
            'summary' => $summary,
            'company' => $context['company'] ?? 'PharmaVerify',
            'footer' => $context['footer'] ?? 'Generated by PharmaVerify',
            'generatedBy' => $context['generated_by'] ?? '-',
            'generatedAt' => Carbon::now()->format('d M Y H:i'),
            'filterLine' => $this->describeFilters($context['filters'] ?? []),
            'truncated' => $context['truncated'] ?? false,
        ]);

        $pdf->setPaper('a4', count($definition->columns) > 8 ? 'landscape' : 'portrait');

        return $pdf->download($this->fileName($definition, 'pdf'));
    }

    private function excelValue(mixed $value, string $type): mixed
    {
        if ($value === null) {
            return '';
        }

        return match ($type) {
            'decimal', 'money' => (float) $value,
            'number' => (int) $value,
            default => $value,
        };
    }

    private function defaultWidth(string $type): int
    {
        return match ($type) {
            'date' => 13,
            'datetime' => 18,
            'decimal', 'money', 'number' => 14,
            default => 18,
        };
    }

    /**
     * @param  array<string, mixed>  $filters
     */
    private function describeFilters(array $filters): string
    {
        $parts = [];

        foreach ($filters as $key => $value) {
            if ($value === null || $value === '' || in_array($key, ['page', 'per_page', 'format', 'sort_by', 'sort_dir'], true)) {
                continue;
            }

            $parts[] = ucwords(str_replace('_', ' ', (string) $key)).': '.(is_array($value) ? implode(', ', $value) : $value);
        }

        return implode('  |  ', $parts);
    }

    private function fileName(ReportDefinition $definition, string $extension): string
    {
        return sprintf('%s-%s.%s', Str::slug($definition->title), Carbon::now()->format('Ymd-His'), $extension);
    }

    private function columnLetter(int $index): string
    {
        return \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($index);
    }
}
