<?php

namespace Database\Seeders;

use App\Models\AppSetting;
use Illuminate\Database\Seeder;

class AppSettingSeeder extends Seeder
{
    public function run(): void
    {
        $settings = [
            ['general', 'company_name', 'Redmind Pharmacy Group', 'string', 'Company Name', 'Shown on reports and exported documents.'],
            ['general', 'report_footer', 'Generated by PharmaVerify', 'string', 'Report Footer', 'Footer text printed on every PDF report.'],
            ['general', 'date_format', 'dd MMM yyyy', 'string', 'Date Format', 'Display format used across the application.'],
            ['stock', 'default_uom', 'EA', 'string', 'Default Unit of Measure', 'Applied when an imported row has no unit of measure.'],
            ['stock', 'expiry_warning_days', '90', 'integer', 'Expiry Warning (days)', 'Stock expiring within this many days is highlighted.'],
            ['verification', 'variance_tolerance', '0', 'integer', 'Variance Tolerance', 'Variance within this quantity is treated as acceptable.'],
            ['onedrive', 'onedrive_folder', 'PharmaVerify/FinalOutput', 'string', 'OneDrive Folder', 'Destination folder for the final output file.'],
        ];

        foreach ($settings as [$group, $key, $value, $type, $label, $description]) {
            AppSetting::updateOrCreate(
                ['key_name' => $key],
                [
                    'group_name' => $group,
                    'value' => $value,
                    'value_type' => $type,
                    'label' => $label,
                    'description' => $description,
                    'is_editable' => true,
                ]
            );
        }
    }
}
