<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $definition->title }}</title>
    <style>
        @page { margin: 20px 22px 42px 22px; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 8.5px; color: #1B2A28; }
        .masthead { border-bottom: 2px solid #0F5D4C; padding-bottom: 8px; margin-bottom: 10px; }
        .brand { font-size: 13px; font-weight: bold; color: #0F5D4C; letter-spacing: .4px; }
        .title { font-size: 15px; font-weight: bold; margin-top: 3px; }
        .description { color: #5F6B6A; margin-top: 2px; }
        .meta { margin-top: 6px; color: #5F6B6A; font-size: 7.5px; }
        .meta span { margin-right: 14px; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        thead th {
            background: #0F5D4C; color: #fff; text-align: left;
            padding: 5px 6px; font-size: 8px; font-weight: bold;
            border: 1px solid #0F5D4C;
        }
        tbody td { padding: 4px 6px; border: 1px solid #D6DEDD; vertical-align: top; }
        tbody tr:nth-child(even) td { background: #F5F8F7; }
        td.num { text-align: right; }
        td.neg { color: #B3261E; font-weight: bold; }
        td.pos { color: #1B6E3C; font-weight: bold; }
        .empty { padding: 18px; text-align: center; color: #5F6B6A; border: 1px dashed #C7D2D0; margin-top: 10px; }
        .summary { margin-top: 12px; width: 60%; }
        .summary th { background: #EDF3F1; color: #1B2A28; border: 1px solid #D6DEDD; padding: 4px 6px; text-align: left; }
        .summary td { border: 1px solid #D6DEDD; padding: 4px 6px; text-align: right; }
        .notice { margin-top: 8px; color: #8A6D00; font-size: 7.5px; }
        footer { position: fixed; bottom: -26px; left: 0; right: 0; height: 24px;
                 border-top: 1px solid #D6DEDD; padding-top: 5px;
                 color: #5F6B6A; font-size: 7.5px; }
        .pagenum:after { content: counter(page); }
    </style>
</head>
<body>

<footer>
    {{ $footer }} &nbsp;|&nbsp; {{ $definition->title }} &nbsp;|&nbsp; Page <span class="pagenum"></span>
</footer>

<div class="masthead">
    <div class="brand">{{ $company }}</div>
    <div class="title">{{ $definition->title }}</div>
    <div class="description">{{ $definition->description }}</div>
    <div class="meta">
        <span><strong>Generated:</strong> {{ $generatedAt }}</span>
        <span><strong>Generated by:</strong> {{ $generatedBy }}</span>
        <span><strong>Records:</strong> {{ count($rows) }}</span>
    </div>
    @if ($filterLine !== '')
        <div class="meta"><span><strong>Filters:</strong> {{ $filterLine }}</span></div>
    @endif
</div>

@if (count($rows) === 0)
    <div class="empty">No records matched the selected filters.</div>
@else
    <table>
        <thead>
        <tr>
            @foreach ($definition->columns as $column)
                <th>{{ $column['label'] }}</th>
            @endforeach
        </tr>
        </thead>
        <tbody>
        @foreach ($rows as $row)
            <tr>
                @foreach ($definition->columns as $column)
                    @php
                        $type = $column['type'] ?? 'text';
                        $value = $row[$column['key']] ?? null;
                        $numeric = in_array($type, ['decimal', 'money', 'number'], true);
                        $variance = $column['key'] === 'variance_qty' || $column['key'] === 'net_variance';
                        $class = $numeric ? 'num' : '';
                        if ($variance && $value !== null) {
                            $class .= $value < 0 ? ' neg' : ($value > 0 ? ' pos' : '');
                        }
                    @endphp
                    <td class="{{ trim($class) }}">
                        @if ($value === null || $value === '')
                            &ndash;
                        @elseif ($type === 'money')
                            {{ number_format((float) $value, 2) }}
                        @elseif ($type === 'decimal')
                            {{ rtrim(rtrim(number_format((float) $value, 3, '.', ''), '0'), '.') ?: '0' }}
                        @else
                            {{ $value }}
                        @endif
                    </td>
                @endforeach
            </tr>
        @endforeach
        </tbody>
    </table>
@endif

@if (! empty($summary))
    <table class="summary">
        <thead><tr><th colspan="2">Summary</th></tr></thead>
        <tbody>
        @foreach ($summary as $label => $value)
            <tr>
                <th>{{ ucwords(str_replace('_', ' ', $label)) }}</th>
                <td>{{ is_float($value) ? rtrim(rtrim(number_format($value, 3, '.', ''), '0'), '.') : $value }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endif

@if ($truncated)
    <div class="notice">
        This export was limited to the first 20,000 records. Apply additional filters to export a narrower set.
    </div>
@endif

</body>
</html>
