<#
.SYNOPSIS
    Writes the configuration for this particular installation.

.DESCRIPTION
    Every PharmaVerify installation needs a .env that no other installation
    shares: its own application key, its own database password, its own address.
    Shipping one would hand every pharmacy the same encryption key, so this is
    generated on the machine and never packaged.

    Lives in ProgramData rather than Program Files. Program Files is read-only
    for standard users and is replaced wholesale on upgrade, which would take
    the configuration with it; the backend is pointed at this copy instead.

    Existing configuration is preserved by default. An upgrade must not silently
    change the database a pharmacy's stock history lives in.

.PARAMETER InstallRoot
    Where the application files are.

.PARAMETER ServerAddress
    Hostname or IP the application is reached on. Used for APP_URL and CORS.

.PARAMETER Port
    Port the web server listens on.

.PARAMETER DbHost / DbPort / DbName / DbUser / DbPassword
    Database connection. DbPassword is a SecureString and is never logged.

.PARAMETER Force
    Overwrites existing configuration. Only for a deliberate reconfigure.

.PARAMETER AdditionalOrigins
    Extra origins to allow in CORS_ALLOWED_ORIGINS, beyond the app's own URL.
    For a second PC or browser reaching this installation by its LAN IP rather
    than the hostname.

.EXAMPLE
    .\Set-Environment.ps1 -ServerAddress pharmaverify.local -DbPassword $secure
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [string] $InstallRoot = (Join-Path ${env:ProgramFiles} 'PharmaVerify'),
    [Parameter(Mandatory)] [string] $ServerAddress,
    [int]    $Port = 8000,

    [ValidateSet('sqlsrv', 'mysql')] [string] $DbConnection = 'sqlsrv',
    [string] $DbHost = '127.0.0.1',
    [int]    $DbPort = 1433,
    [string] $DbName = 'pharmaverify',
    [string] $DbUser = 'pharmaverify',
    [Parameter(Mandatory)] [securestring] $DbPassword,

    [switch] $Force,
    [string[]] $AdditionalOrigins
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

. (Join-Path $PSScriptRoot 'Common.ps1')

$configDir = Join-Path $script:DataRoot 'config'
$envPath   = Join-Path $configDir '.env'
$backend   = Join-Path $InstallRoot 'backend'

if (-not (Test-Path $configDir)) {
    New-Item -ItemType Directory -Path $configDir -Force | Out-Null
}

# ------------------------------------------------------ keep what is already there

if ((Test-Path $envPath) -and -not $Force) {
    Write-Log 'Existing configuration found; leaving it untouched.' -Level OK
    Write-Log 'Re-run with -Force to replace it. On an upgrade, that would change which database the pharmacy uses.' -Level INFO
    exit 0
}

# --------------------------------------------------------------- application key

# Reused if one already exists. The key encrypts session and queue payloads;
# changing it on an upgrade signs everyone out and makes existing encrypted
# values unreadable.
$appKey = $null

if (Test-Path $envPath) {
    $existingKey = Select-String -Path $envPath -Pattern '^APP_KEY=(.+)$' -ErrorAction SilentlyContinue |
        Select-Object -First 1
    if ($existingKey) { $appKey = $existingKey.Matches[0].Groups[1].Value.Trim() }
}

if (-not $appKey) {
    # 32 random bytes, base64, as Laravel expects. Generated with the platform
    # cryptographic RNG rather than Get-Random, which is not suitable for keys.
    $bytes = [byte[]]::new(32)
    # RandomNumberGenerator.Fill is a .NET 6+ API and does not exist on .NET
    # Framework, which is what Windows PowerShell 5.1 runs on — and 5.1 is
    # what the installer invokes (powershell.exe, not pwsh). RNGCryptoServiceProvider
    # is the 5.1-safe equivalent.
    $rng = [System.Security.Cryptography.RNGCryptoServiceProvider]::new()
    $rng.GetBytes($bytes)
    $rng.Dispose()
    $appKey = 'base64:' + [Convert]::ToBase64String($bytes)
    Write-Secret 'Application key'
} else {
    Write-Log 'Reusing the existing application key.' -Level OK
}

# ------------------------------------------------------------------- the file

$plainPassword = [System.Net.NetworkCredential]::new('', $DbPassword).Password
$appUrl = "http://${ServerAddress}:${Port}"

# The SPA is same-origin, so this list is belt-and-braces in the common case —
# but a second office PC browsing this installation by its LAN IP rather than
# the hostname should not be refused for want of a header.
$origins = [System.Collections.Generic.List[string]]::new()
$origins.Add($appUrl)
foreach ($origin in $AdditionalOrigins) {
    if ($origin -and -not $origins.Contains($origin)) { $origins.Add($origin) }
}
$corsOrigins = $origins -join ','

$content = @"
# PharmaVerify — configuration for this installation.
#
# Generated by the installer. Machine-specific: do not copy this file to
# another PC, and do not commit it anywhere.
#
# Written $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')

APP_NAME=PharmaVerify
APP_ENV=production
APP_KEY=$appKey
APP_DEBUG=false
APP_URL=$appUrl

LOG_CHANNEL=stack
LOG_LEVEL=warning

DB_CONNECTION=$DbConnection
DB_HOST=$DbHost
DB_PORT=$DbPort
DB_DATABASE=$DbName
DB_USERNAME=$DbUser
DB_PASSWORD="$plainPassword"

SESSION_DRIVER=file
SESSION_LIFETIME=120
CACHE_STORE=file
QUEUE_CONNECTION=sync

# The front end is served from this same address, so it asks for a relative
# /api and needs no rebuild when the address changes.
FRONTEND_URL=$appUrl
CORS_ALLOWED_ORIGINS="$corsOrigins"

# Sent only over HTTPS. Harmless until the site has a certificate.
SECURITY_HSTS_ENABLED=true
SECURITY_HSTS_MAX_AGE=31536000
SECURITY_HSTS_INCLUDE_SUBDOMAINS=true
"@

if ($PSCmdlet.ShouldProcess($envPath, 'Write configuration')) {
    # UTF8 without a byte-order mark: a BOM ends up inside the first variable's
    # name and Laravel then cannot find APP_NAME.
    [System.IO.File]::WriteAllText($envPath, $content, [System.Text.UTF8Encoding]::new($false))

    # Readable only by administrators and the service account. It holds the
    # database password in clear text, as Laravel requires.
    $acl = Get-Acl $envPath
    $acl.SetAccessRuleProtection($true, $false)
    foreach ($who in @('BUILTIN\Administrators', 'NT AUTHORITY\SYSTEM', 'IIS_IUSRS')) {
        try {
            $acl.AddAccessRule([System.Security.AccessControl.FileSystemAccessRule]::new(
                $who, 'Read', 'Allow'))
        } catch {
            Write-Log "Could not grant read access to $who (it may not exist on this machine)." -Level WARN
        }
    }
    try {
        $acl.AddAccessRule([System.Security.AccessControl.FileSystemAccessRule]::new(
            'BUILTIN\Administrators', 'FullControl', 'Allow'))
        Set-Acl -Path $envPath -AclObject $acl
        Write-Log 'Configuration file restricted to administrators and the web server.' -Level OK
    } catch {
        Write-Log 'Could not restrict permissions on the configuration file. Check it manually.' -Level WARN
    }

    Write-Secret 'Database password'
    Write-Log "Configuration written to $envPath" -Level OK
    Write-Log "PharmaVerify will be served at $appUrl" -Level INFO
}

# ----------------------------------------------- point the application at it

# Laravel looks for .env beside the application. A junction keeps the single
# copy in ProgramData authoritative while satisfying that expectation, and
# survives the application folder being replaced on upgrade.
$link = Join-Path $backend '.env'

if ((Test-Path $backend) -and $PSCmdlet.ShouldProcess($link, 'Link configuration into the application')) {
    if (Test-Path $link) { Remove-Item $link -Force }
    New-Item -ItemType HardLink -Path $link -Target $envPath -ErrorAction SilentlyContinue | Out-Null

    if (-not (Test-Path $link)) {
        # Hard links need both paths on one volume. Copy instead, and say so:
        # the two copies then have to be kept in step by whoever changes one.
        Copy-Item $envPath $link -Force
        Write-Log 'Configuration copied into the application folder (a link was not possible across volumes).' -Level WARN
    } else {
        Write-Log 'Configuration linked into the application folder.' -Level OK
    }
}
