<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\AppSetting;
use App\Services\Reports\ReportExportService;
use App\Services\Reports\ReportService;
use App\Support\ApiResponse;
use App\Support\Permissions;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class ReportController extends Controller
{
    public function __construct(
        private readonly ReportService $reports,
        private readonly ReportExportService $exports,
    ) {}

    /** The reports this user is allowed to run, with their columns and filters. */
    public function index(Request $request): JsonResponse
    {
        $request->user()->can(Permissions::REPORTS_VIEW) || abort(403);

        return ApiResponse::success($this->reports->catalogue($request->user()));
    }

    /**
     * Runs a report. `format=xlsx` or `format=pdf` returns a download instead
     * of the on-screen result.
     */
    public function show(Request $request, string $report)
    {
        $format = strtolower((string) $request->query('format', 'json'));

        if (in_array($format, ['xlsx', 'excel', 'pdf'], true)) {
            return $this->export($request, $report, $format);
        }

        $result = $this->reports->run($report, $request);
        $paginator = $result['paginator'];

        return ApiResponse::success($result['rows'], null, [
            'report' => $result['definition']->toArray(),
            'summary' => $result['summary'],
            'current_page' => $paginator->currentPage(),
            'per_page' => $paginator->perPage(),
            'total' => $paginator->total(),
            'last_page' => $paginator->lastPage(),
            'from' => $paginator->firstItem(),
            'to' => $paginator->lastItem(),
        ]);
    }

    private function export(Request $request, string $report, string $format)
    {
        $result = $this->reports->collect($report, $request);

        $context = [
            'company' => $this->setting('company_name', 'PharmaVerify'),
            'footer' => $this->setting('report_footer', 'Generated by PharmaVerify'),
            'generated_by' => $request->user()->name,
            'filters' => $request->query(),
            'truncated' => $result['truncated'],
        ];

        activity('report')
            ->causedBy($request->user())
            ->withProperties(['report' => $report, 'format' => $format, 'rows' => count($result['rows'])])
            ->log('Report exported');

        if ($format === 'pdf') {
            return $this->exports->pdf($result['definition'], $result['rows'], $result['summary'], $context);
        }

        return $this->exports->excel($result['definition'], $result['rows'], $result['summary'], $context);
    }

    private function setting(string $key, string $fallback): string
    {
        return AppSetting::where('key_name', $key)->value('value') ?: $fallback;
    }
}
